kind = "DojoContract"
class_hash = "0x41f701950e64b4c79f1fadeef856f9ab98dbf83d65bdafc83257232273deff6"
original_class_hash = "0x41f701950e64b4c79f1fadeef856f9ab98dbf83d65bdafc83257232273deff6"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/starkgo_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "starkgo::systems::actions::actions"
