kind = "DojoContract"
class_hash = "0x3683018bed2f1517f7a8d763b4e382b4f443f807a37112aa3a545562d4d2fb0"
original_class_hash = "0x3683018bed2f1517f7a8d763b4e382b4f443f807a37112aa3a545562d4d2fb0"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/starkgo_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "starkgo::systems::actions::actions"
