kind = "DojoContract"
class_hash = "0x119c8fff70af86e47150bd0ec38b886013a23b1bf7876fbe67c82fb5fb3e0ea"
original_class_hash = "0x119c8fff70af86e47150bd0ec38b886013a23b1bf7876fbe67c82fb5fb3e0ea"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/starkgo_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "starkgo::systems::actions::actions"
