kind = "DojoContract"
class_hash = "0x41e898772b46962656ff5235f1ea98ac6f0e44b059dc6d7fd8f8e74cc4044de"
original_class_hash = "0x41e898772b46962656ff5235f1ea98ac6f0e44b059dc6d7fd8f8e74cc4044de"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/starkgo_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "starkgo::systems::actions::actions"
