kind = "DojoContract"
class_hash = "0x47850e40e198b68c42a21836d8b6a763500231de2965ac8d7c863bf450604f7"
original_class_hash = "0x47850e40e198b68c42a21836d8b6a763500231de2965ac8d7c863bf450604f7"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/starkgo_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "starkgo::systems::actions::actions"
