kind = "DojoContract"
class_hash = "0x6a622c06992d938e5318f457e68309d43975814cc536b78ad5bf591a00aaecd"
original_class_hash = "0x6a622c06992d938e5318f457e68309d43975814cc536b78ad5bf591a00aaecd"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/starkgo_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "starkgo::systems::actions::actions"
