kind = "DojoContract"
class_hash = "0x2c7a0a6b14d6cc8b1c8914bd34a43b53d827284e8938d3a90ad0263c339a5ba"
original_class_hash = "0x2c7a0a6b14d6cc8b1c8914bd34a43b53d827284e8938d3a90ad0263c339a5ba"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/starkgo_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "starkgo::systems::actions::actions"
