[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x7bf4dbc57ac4213d82f13516bae388f7980897fc16fbc64eb6d156a9d739030"
transaction_hash = "0x5703941c492c1836dd00f2a93625b4f4b4161dda1e99c6ac62e3a19236e66c7"
block_number = 3
seed = "starkgo"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x167359df980dc4435a6baf982375ac517e6f138b5a10d93f2a1acf3c17f5b88"
class_hash = "0x27ee1613c2c20aae341a85b655f0d2e70411a5f48604bfca76db41ccae4f4d9"
original_class_hash = "0x27ee1613c2c20aae341a85b655f0d2e70411a5f48604bfca76db41ccae4f4d9"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/starkgo_systems_actions_actions.json"
reads = []
writes = ["Games"]
computed = []
init_calldata = []
name = "starkgo::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x70aae269d11a3f7f9b44d3a0beb184206a111a67b8b3474ca95755ff41a471f"
original_class_hash = "0x70aae269d11a3f7f9b44d3a0beb184206a111a67b8b3474ca95755ff41a471f"
abi = "manifests/dev/abis/deployments/models/starkgo_models_game_games.json"
name = "starkgo::models::game::games"

[[models.members]]
name = "game_id"
type = "felt252"
key = true

[[models.members]]
name = "state"
type = "GameState"
key = false

[[models.members]]
name = "controller"
type = "Option<ContractAddress>"
key = false

[[models.members]]
name = "opponent"
type = "Option<ContractAddress>"
key = false

[[models.members]]
name = "controller_has_black"
type = "bool"
key = false

[[models.members]]
name = "board"
type = "Board"
key = false

[[models.members]]
name = "new_turn_player"
type = "Player"
key = false
