kind = "DojoModel"
class_hash = "0xba83db5b09a7f4b29088967259214f20fc57412ee03ecb800d95e34af8c6f9"
original_class_hash = "0xba83db5b09a7f4b29088967259214f20fc57412ee03ecb800d95e34af8c6f9"
abi = "manifests/dev/abis/base/models/starkgo_models_moves_moves.json"
name = "starkgo::models::moves::moves"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false
