kind = "DojoModel"
class_hash = "0xae4041679e780d457e1c68f020ecf704940bd6d240bd017e37cf05d6e8ea95"
original_class_hash = "0xae4041679e780d457e1c68f020ecf704940bd6d240bd017e37cf05d6e8ea95"
abi = "manifests/dev/abis/base/models/starkgo_models_game_games.json"
name = "starkgo::models::game::games"

[[members]]
name = "game_id"
type = "felt252"
key = true

[[members]]
name = "state"
type = "GameState"
key = false

[[members]]
name = "controller"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "opponent"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "controller_has_black"
type = "StartVote"
key = false

[[members]]
name = "board"
type = "Board"
key = false

[[members]]
name = "new_turn_player"
type = "Player"
key = false
