kind = "DojoModel"
class_hash = "0x75559e62dae9ff34416111cf09a5b6f457f2f0298d806087046866ff5d5ad98"
original_class_hash = "0x75559e62dae9ff34416111cf09a5b6f457f2f0298d806087046866ff5d5ad98"
abi = "manifests/dev/abis/base/models/starkgo_models_game_games.json"
name = "starkgo::models::game::games"

[[members]]
name = "game_id"
type = "felt252"
key = true

[[members]]
name = "state"
type = "GameState"
key = false

[[members]]
name = "controller"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "opponent"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "controller_has_black"
type = "StartVote"
key = false

[[members]]
name = "board"
type = "Board"
key = false

[[members]]
name = "nb_moves"
type = "u32"
key = false

[[members]]
name = "capture"
type = "Capture"
key = false

[[members]]
name = "new_turn_player"
type = "Player"
key = false

[[members]]
name = "result"
type = "GameResult"
key = false
