kind = "DojoModel"
class_hash = "0xe52b5529036f5fbd4985f5e772420e057d624be5cc7a2088aa01167e5da1e3"
original_class_hash = "0xe52b5529036f5fbd4985f5e772420e057d624be5cc7a2088aa01167e5da1e3"
abi = "manifests/dev/abis/base/models/starkgo_models_game_games.json"
name = "starkgo::models::game::games"

[[members]]
name = "game_id"
type = "felt252"
key = true

[[members]]
name = "state"
type = "GameState"
key = false

[[members]]
name = "controller"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "opponent"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "controller_has_black"
type = "StartVote"
key = false

[[members]]
name = "board"
type = "Board"
key = false

[[members]]
name = "capture"
type = "Capture"
key = false

[[members]]
name = "new_turn_player"
type = "Player"
key = false

[[members]]
name = "result"
type = "GameResult"
key = false
