kind = "DojoModel"
class_hash = "0x400e8ccd7717ca849730ea52c92171409fdd9dcb896e8d58ef3a6d123bd2989"
original_class_hash = "0x400e8ccd7717ca849730ea52c92171409fdd9dcb896e8d58ef3a6d123bd2989"
abi = "manifests/dev/abis/base/models/starkgo_models_game_games.json"
name = "starkgo::models::game::games"

[[members]]
name = "game_id"
type = "felt252"
key = true

[[members]]
name = "state"
type = "GameState"
key = false

[[members]]
name = "controller"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "opponent"
type = "Option<ContractAddress>"
key = false

[[members]]
name = "controller_has_black"
type = "StartVote"
key = false

[[members]]
name = "board"
type = "Board"
key = false

[[members]]
name = "previous_board"
type = "Board"
key = false

[[members]]
name = "nb_moves"
type = "u32"
key = false

[[members]]
name = "capture"
type = "Capture"
key = false

[[members]]
name = "new_turn_player"
type = "Player"
key = false

[[members]]
name = "result"
type = "GameResult"
key = false
